### ISSUE TITLE
debian support

### ISSUE THREAD

**Issue by ekorian** [dreibh/netperfmeter#2] opened 2019-04-24 15:05 UTC
I can't run the server/listener on debian stretch 9.5, kernel 4.9

user@machine:~/$ sudo netperfmeter 9000
Network Performance Meter - Version 1.0

-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Global Parameters:
   - Runtime           = until manual stop
   - Active Node Name  = Client
   - Passive Node Name = Server
   - Local Address(es) = (any)
   - Logging Verbosity = 9

NOTE: Compiled with MPTCP support, but unable to initialize it: Operation not permitted!
NOTE: Your kernel does not provide DCCP support.
ERROR: Failed to configure DCCP service code on DCCP socket (DCCP_SOCKOPT_SERVICE option) - Bad file descriptor!

**Comment by dreibh** [comment] 2019-07-25 13:32
Which version of NetPerfMeter are you trying?

**Comment by dreibh** [comment] 2019-12-05 13:42
The error looks like a bug in an old version of NetPerfMeter, which should be fixed in the current version of NetPerfMeter. Can you reproduce the error with the current version of NetPerfMeter (1.8.5)?

**Comment by tpelado** [comment] 2020-04-01 15:02
Hello, I'm commenting on this cause I've been trying to use netperfmeter in debian VMs, but I have met the same error as above (DCCP not supported). Debian Buster has an outdated version in the repositories :
```
tanguy@debianTEST:~$ apt search netperfmeter
En train de trier... Fait
Recherche en texte intégral... Fait
netperfmeter/stable,now 1.2.3-1+b1 amd64  [installé]
Network Performance Meter
 ```

I have tried to build from sources, but I've encountered errors relating to undefined references to ext_setsockopt.

Is there any workaround to use TCP only on the passive side ? I do not need support for DCCP.

Also, while I doubt this can be done due to the very way they work, any chance of using netperfmeter in a LXC container ?

Thanks

**Comment by dreibh** [comment] 2021-02-04 12:49
Version 1.2.3 is highly out of date. The current version is 1.8.6. Did you try the latest version from https://www.uni-due.de/~be0001/netperfmeter/ (or from "master" in the GitHub repository)?

The current CI tests for Debian Stretch, Buster and Sid show no build issues (see https://travis-ci.org/github/dreibh/netperfmeter). If you see a build issue, please provide more details, particularly the full output of the cmake and make runs.

**Closed** 2024-02-10 14:57 UTC
Labels: bug, question
